[Integrated Search bar] Modify Search List for type
FieldAssist/fa_flutter_ui_kit pull request #28
Opened 2021-12-01 07:29 UTC by Heleo2705

+ Refractor Integrated Search Bar
+ Add Integrated Search text Field

## Description

Modify Search List, Search Bar and Integrated Search Text Field
Links :

No Link(s) added.

## Commits

## Tests

I added the following tests:

No Test(s) added.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read and followed the [Best Practices Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] Added relevant reviewers.

## Breaking Change

- [] No, no existing tests failed.
- [x] Yes, this is a breaking change.

## Should be merge type:

- [ ] Squash and merge
- [x] Rebase and merge

[Best Practices Guide]: https://techdocs.fieldassist.io/guide/flutter-docs/best-practices.html

2021-12-01 14:25 UTC, apgapg commented
I hope other apps are not affected with this change @Heleo2705

2021-12-01 14:31 UTC, Heleo2705 commented
I have to discuss some default cases or otherwise it'll cause breaking of apps. I'll have a meeting with GT devs to discuss the same. We're currently using this branch as ref in MT so it's safe

2021-12-03 11:03 UTC, TusharFA requested changes

2021-12-03 11:03 UTC, TusharFA commented on lib/src/modules/common/search_list/integrated_search_bar.dart
> +                  child: IntegratedSearchTextField(
This is UI change. Handle it separately.

2022-04-19 08:25 UTC, closed without merging